name: AWS CD
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  DeployToAWS:
    environment: 
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      
      # 1. Configuração inicial
      - name: Determine AWS account ID
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOMOLOG }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
          else
            echo "Invalid branch name!" && exit 1
          fi
          echo "AWS_REGION=sa-east-1" >> $GITHUB_ENV

      # 2. Instalação de dependências
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # 3. Configuração AWS
      - name: Setup AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: sa-east-1
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: github-action
          role-duration-seconds: 3600

      # 4. Bootstrap (agora com região definida)
      - name: Bootstrap CDK
        run: |
          cd iac
          npm install
          cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}

      # 5. Build e Deploy
      - name: Build and Export
        run: |
          npm install
          npm run build

      - name: Verify Bootstrap
        run: |
          cd iac
          aws ssm get-parameter --name /cdk-bootstrap/hnb659fds/version --region ${{ env.AWS_REGION }} || cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}

      - name: Deploy with CDK
        run: |
          cd iac
          cdk synth
          cdk deploy --require-approval never
        env:
          AWS_REGION: sa-east-1

      - name: Set CloudFront ID
        run: |
          CLOUD_FRONT_ID=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='${{env.PROJECT_NAME}}DistributionId${{github.ref_name}}'].OutputValue" --output text)
          echo "CLOUD_FRONT_ID='$CLOUD_FRONT_ID'" >> $GITHUB_ENV
      - name: Set AWS Bucket
        run: |
          AWS_BUCKET=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='${{env.PROJECT_NAME}}BucketName${{github.ref_name}}'].OutputValue" --output text)
          echo "AWS_BUCKET='$AWS_BUCKET'" >> $GITHUB_ENV
      - name: Upload to S3
        run: aws s3 cp dist s3://${{env.AWS_BUCKET}}/ --recursive --region sa-east-1
      - name: Clear CDN cache
        run: aws cloudfront create-invalidation --distribution-id ${{env.CLOUD_FRONT_ID}} --paths "/*" --region us-east-1